# Educational Runner Game - Netlify Configuration
[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://unpkg.com; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800" # 1 week

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800" # 1 week

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400" # 1 day

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600" # 1 hour

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 1 month

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 1 month

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Custom error pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Enable gzip compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true