name: Deploy Educational Runner Game

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Validate deployment files
      run: |
        # Check that all required files exist
        test -f index.html || (echo "Missing index.html" && exit 1)
        test -f main.js || (echo "Missing main.js" && exit 1)
        test -f sw.js || (echo "Missing sw.js" && exit 1)
        test -d game || (echo "Missing game directory" && exit 1)
        test -d data || (echo "Missing data directory" && exit 1)
        echo "✅ All required files present"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          test/**
          scripts/**
          node_modules/**
          .github/**
          *.md
          package*.json
          jest.config.js
          .gitignore
          .lighthouserc.json